server.port: 8902

spring:
  aop:
    auto: true
  application:
    version: v1
    cnname: xxx微服务模块儿-v1
    name: xxx-module-${spring.application.version}
  messages:
    encoding: UTF-8
    cache-seconds: 3600
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hkwl?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/ml/test/xxx/mapper/simple/*.xml
  type-aliases-package: com.ml.test.xxx.model.simple,com.ml.test.xxx.model.complex,com.ml.test.xxx.request

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management.security.enabled: false

logging.level.com.ml.test.xxx.mapper: debug


eureka:
  instance:
    metadataMap.alarmEmail: ITdbus.list@creditease.cn
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl.defaultZone: http://localhost:9090/eureka/